# Publish multiple feature branches with the same pipeline, or just one main publish by entering targetGithubBranch value at runtime.
# When a targetBranch parameter is passed to the Zoomin upload template, a new bundle is created with the 
# branch name appended to the repository name to create the cust.properties file and will not overwrite the main 
# published bundle. If default value of targetGithubBranch, 'main', is passed to the template, the bundle name will be the specified 
# Repository name without the branch name appended to it. 

parameters:
  # Defined during pipeline build, not necessary if main/master is only intended publish branch
  - name: targetGithubBranch
    type: string
    default: main
    values:
      - main
      - single-toc

  - name: publishSite
    displayName: Publish Site
    type: string
    default: 'dev'
    values:
    - dev
    - production

trigger: 
- none

resources:
  repositories:
  - repository: OpsGuildAutomationRepository
    type: git
    name: Engineering/OpsGuild.Automation
  - repository: DocSource
    type: github
    name: osisoft/$(gitRepository) 
    ref: $(targetBranch) 
    # Must point to branch that contains zoomin classification file
    endpoint: zoomin-content-pipelines-github

variables:
  - name: gitRepository
    value: PI-Adapter-MQTT-Docs
  - name: targetBranch 
    # New variable added strictly for publishing different feature branches
    value: ${{ parameters.targetGithubBranch }} 
    # Change to desired branch name: i.e: develop
  - name: publication
    value: 'PI Adapter for MQTT'

jobs:
  - template: Pipelines/Templates/Zoomin/UploadGithubToZoomin.job.v0.yml@OpsGuildAutomationRepository
    parameters:
      gitRepo: $(gitRepository)
      targetBranch: $(targetBranch) 
      # Necessary parameter in order for a new bundle to be produced specific to the branch
      publication: $(publication) 
      # Optional Parameter, defaults to gitRepository variable - used in custom.properties file and defines Booktitle of bundle
      publishSite: ${{ parameters.publishSite }} 
      # Optional parameter to be used when publishing to different Zoomin sites, currently defaults to publishing to the Zoomin dev site
      buildSteps: # Must be used in this order 
        - checkout: DocSource
          clean: true
          persistCredentials: true
          submodules: recursive
          displayName: Checkout Submodules
        - powershell: |

            cd $env:Build_SourcesDirectory\$(gitRepository)\
            git submodule init
            git submodule update

            echo "Submodule checkout/pull - content\main"
            cd content\main
            git checkout main-remove-toc
            git rev-parse HEAD
            dir
            cd ..\..
        - template: ../templates/T_DocFxAndPublishToGithub.yml  
          # Add DocFX Template to buildSteps
          parameters: 
            publishToGithub: false 
            # Required Parameter and value, should be set to false because gh-pages doesn't need to be published
            srcDir: $(Build.SourcesDirectory)/$(gitRepository) 
            # Required parameter, necessary to include gitRepository name due to multiple repository checkouts 
        - checkout: OpsGuildAutomationRepository 
          # Checkout repository in order to reference powershell scripts from Zoomin template 
